services:
  - type: web
    name: expense-iq-backend
    runtime: java
    buildCommand: mvn clean install -DskipTests
    startCommand: java -Dserver.port=$PORT $JAVA_OPTS -jar target/*.jar
    envVars:
      - key: JAVA_VERSION
        value: 17
